# Generated by Django 5.1.1 on 2024-10-15 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CorData",
            fields=[
                ("cor_id", models.AutoField(primary_key=True, serialize=False)),
                ("cor_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "기업 테이블",
                "verbose_name_plural": "기업 테이블",
                "db_table": "Cor_data",
            },
        ),
        migrations.CreateModel(
            name="NewsData",
            fields=[
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("news_title", models.CharField(max_length=200)),
                ("news_link", models.CharField(max_length=200)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "cor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.cordata"
                    ),
                ),
            ],
            options={
                "verbose_name": "데이터 테이블",
                "verbose_name_plural": "데이터 테이블",
                "db_table": "News_data",
            },
        ),
        migrations.CreateModel(
            name="SentimentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_link", models.CharField(max_length=200)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=8,
                    ),
                ),
                ("accuracy", models.FloatField()),
                (
                    "cor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="search.cordata"
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="search.newsdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "감정분석 테이블",
                "verbose_name_plural": "감정분석 테이블",
                "db_table": "Sentiment_data",
            },
        ),
    ]
